// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {main} from '../models';

export function AddAccount(arg1:service.AccountReq):Promise<main.BoolResult>;

export function CheckForUpdates(arg1:string):Promise<main.UpdateResult>;

export function DeleteAccount(arg1:string):Promise<main.BoolResult>;

export function ExportConfig(arg1:service.AppConfig):Promise<main.BoolResult>;

export function GetConfig():Promise<main.ConfigResult>;

export function GetCourses(arg1:string):Promise<main.CourseListResult>;

export function GetDashboard():Promise<main.DashboardResult>;

export function GetDataDir():Promise<main.StringResult>;

export function GetPlatformSupport():Promise<main.PlatformListResult>;

export function GetRecentLogs(arg1:number):Promise<main.StringListResult>;

export function GetTaskStatuses():Promise<main.TaskStatusListResult>;

export function ImportConfig():Promise<main.ConfigResult>;

export function ListAccounts():Promise<main.AccountListResult>;

export function OpenDataDir():Promise<main.BoolResult>;

export function OpenURL(arg1:string):Promise<main.BoolResult>;

export function ReadICVECookie():Promise<main.StringResult>;

export function SaveConfig(arg1:service.AppConfig):Promise<main.BoolResult>;

export function StartICVECookieCapture(arg1:string):Promise<main.StringResult>;

export function StartTask(arg1:string):Promise<main.BoolResult>;

export function StopTask(arg1:string):Promise<main.BoolResult>;

export function TailLogFile(arg1:number):Promise<main.StringListResult>;

export function TestAIConfig():Promise<main.StringResult>;

export function UpdateAccount(arg1:service.AccountReq):Promise<main.BoolResult>;
