// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1) {
  return window['go']['main']['App']['AddAccount'](arg1);
}

export function CheckForUpdates(arg1) {
  return window['go']['main']['App']['CheckForUpdates'](arg1);
}

export function DeleteAccount(arg1) {
  return window['go']['main']['App']['DeleteAccount'](arg1);
}

export function ExportConfig(arg1) {
  return window['go']['main']['App']['ExportConfig'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCourses(arg1) {
  return window['go']['main']['App']['GetCourses'](arg1);
}

export function GetDashboard() {
  return window['go']['main']['App']['GetDashboard']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetPlatformSupport() {
  return window['go']['main']['App']['GetPlatformSupport']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetTaskStatuses() {
  return window['go']['main']['App']['GetTaskStatuses']();
}

export function ImportConfig() {
  return window['go']['main']['App']['ImportConfig']();
}

export function ListAccounts() {
  return window['go']['main']['App']['ListAccounts']();
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function ReadICVECookie() {
  return window['go']['main']['App']['ReadICVECookie']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartICVECookieCapture(arg1) {
  return window['go']['main']['App']['StartICVECookieCapture'](arg1);
}

export function StartTask(arg1) {
  return window['go']['main']['App']['StartTask'](arg1);
}

export function StopTask(arg1) {
  return window['go']['main']['App']['StopTask'](arg1);
}

export function TailLogFile(arg1) {
  return window['go']['main']['App']['TailLogFile'](arg1);
}

export function TestAIConfig() {
  return window['go']['main']['App']['TestAIConfig']();
}

export function TestQuestionBankConfig() {
  return window['go']['main']['App']['TestQuestionBankConfig']();
}

export function UpdateAccount(arg1) {
  return window['go']['main']['App']['UpdateAccount'](arg1);
}
