export const APP_VERSION = "0.2.5"
export const SOURCE_REPO_URL = "https://github.com/yatori-dev/yatori-go-console"
export const PROJECT_REPO_URL = "https://github.com/yuanglove/yatori-go-desktop"
export const PROJECT_RELEASES_URL = "https://github.com/yuanglove/yatori-go-desktop/releases"
export const PROJECT_REPO_API_URL = "https://api.github.com/repos/yuanglove/yatori-go-desktop"
